#!/bin/bash
### BEGIN INIT INFO
# Provides:          cloud-portal
# Required-Start:    docker
# Required-Stop:
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Description:       Cloud Portal Init Script
### END INIT INFO

# set compose file location
composeFile="{{ application_folder }}/compose/docker-compose.yml"

# include docker-compose-wrapper script
source /usr/local/bin/docker-compose-wrapper